spring.application.name=Ooredoo
server.port=8089

### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/Ooredoo?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto= update
#Logging
logging.level.root = info
logging.pattern.console= %d{yyyy-MM-dd HH:mm:ss} -%level -%logger{60} %msg %n

# Context path
server.servlet.context-path=/Ooredoo
security.jwt.secret-key=2B7E151628AED2A6ABF7158809CF4F3C2D6E4DDE47A56FAE0D3A7CE5D1F9B8A3
security.jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ryhab.boulaares@gmail.com
spring.mail.password=meafpwgdnksxetrc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.from=ryhab.boulaares@gmail.com



